# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fedmed.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fedmed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65\x64med.proto\x12\x06\x66\x65\x64med\")\n\x12HealthCheckRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\"Z\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12!\n\x19\x61uthenticated_hospital_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\\\n\x12\x46\x65\x64MedCoordination\x12\x46\n\x0bHealthCheck\x12\x1a.fedmed.HealthCheckRequest\x1a\x1b.fedmed.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedmed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=24
  _globals['_HEALTHCHECKREQUEST']._serialized_end=65
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=67
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=157
  _globals['_FEDMEDCOORDINATION']._serialized_start=159
  _globals['_FEDMEDCOORDINATION']._serialized_end=251
# @@protoc_insertion_point(module_scope)
