# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fedmed_pb2 as fedmed__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fedmed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FedMedCoordinationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/fedmed.FedMedCoordination/HealthCheck',
                request_serializer=fedmed__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=fedmed__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.SubmitEncryptedUpdate = channel.unary_unary(
                '/fedmed.FedMedCoordination/SubmitEncryptedUpdate',
                request_serializer=fedmed__pb2.SubmitEncryptedUpdateRequest.SerializeToString,
                response_deserializer=fedmed__pb2.SubmitEncryptedUpdateResponse.FromString,
                _registered_method=True)


class FedMedCoordinationServicer:
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Proves a hospital can reach the server over an authenticated TLS/mTLS channel.
        `authenticated_hospital_id` is filled in by the server from the verified client
        certificate's Common Name -- never trusted from the request body alone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEncryptedUpdate(self, request, context):
        """Module 9: submits one hospital's CKKS-encrypted model update for this round. The
        server (server/federated/encrypted/aggregator.py) only ever stores and
        homomorphically aggregates these ciphertexts -- it holds no CKKS secret key and
        never decrypts an individual submission. Caller identity is re-verified against the
        already-authenticated client certificate, exactly like HealthCheck.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedMedCoordinationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=fedmed__pb2.HealthCheckRequest.FromString,
                    response_serializer=fedmed__pb2.HealthCheckResponse.SerializeToString,
            ),
            'SubmitEncryptedUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEncryptedUpdate,
                    request_deserializer=fedmed__pb2.SubmitEncryptedUpdateRequest.FromString,
                    response_serializer=fedmed__pb2.SubmitEncryptedUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedmed.FedMedCoordination', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedmed.FedMedCoordination', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FedMedCoordination:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedCoordination/HealthCheck',
            fedmed__pb2.HealthCheckRequest.SerializeToString,
            fedmed__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitEncryptedUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.FedMedCoordination/SubmitEncryptedUpdate',
            fedmed__pb2.SubmitEncryptedUpdateRequest.SerializeToString,
            fedmed__pb2.SubmitEncryptedUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
